# Generated by Django 3.2.7 on 2021-09-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_remove_idea_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='idea',
            field=models.CharField(max_length=80),
        ),
    ]
