# Generated by Django 3.2.7 on 2021-09-11 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ideas', '0003_alter_idea_idea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='idea',
        ),
        migrations.AddField(
            model_name='idea',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='idea',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='idea',
            name='idea_message',
            field=models.CharField(max_length=250),
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_code', models.CharField(max_length=15)),
                ('date', models.DateField(auto_now_add=True)),
                ('closed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='idea',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ideas.board'),
            preserve_default=False,
        ),
    ]
