# Generated by Django 3.2.7 on 2021-09-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0004_auto_20210911_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='board',
        ),
        migrations.AddField(
            model_name='board',
            name='items',
            field=models.ManyToManyField(to='ideas.Idea'),
        ),
    ]
