# Generated by Django 3.2.7 on 2021-09-12 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0005_auto_20210911_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='items',
        ),
        migrations.AddField(
            model_name='idea',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ideas.board'),
            preserve_default=False,
        ),
    ]
