# Generated by Django 3.2.7 on 2021-09-10 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='comment',
        ),
    ]
