# Generated by Django 3.2.7 on 2021-09-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='voting',
        ),
        migrations.AlterField(
            model_name='topic',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
