# Generated by Django 3.2.7 on 2021-09-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0003_remove_topic_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
    ]
