# Generated by Django 3.2.7 on 2021-09-10 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0006_auto_20210910_1024'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Votes',
        ),
    ]
